### PR TITLE
#158241793 Purchase of Digital Products

### PR DESCRIPTION
**Pull request by emmabaye**
#### What does this PR do?
Implements feature for downloading digital products after payment. 
- ensure user gets download mail after purchase
- ensure user can download digital product on Reaction commerce
- ensure admin can view digital product details before editing
#### Description of Task to be completed?
N/A
#### How should this be manually tested?
Purchase a digital product on the platform. A mail will be sent to the user and also a download link is available after purchase.
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
#158241793
#### Screenshots (if appropriate)

Questions:

### CODE REVIEW

**Comment by chuzksy-codeactive** [comment]
Good work @emmabaye. But I noticed you don't have the homepage in your PR and the navbar has not been updated.

This is what we have in the staging branch
screencapture-thorin-rc-staging-pr-14-herokuapp-2018-06-26-09_03_14

And this what you have on ur PR
screencapture-thorin-rc-staging-pr-13-herokuapp-product-ftnkh46dsci6ybxvk-2018-06-26-09_03_37

I suggest you pull from staging branch to update what you have on your PR

**Review by amarachukwu-agbo — COMMENTED** [review]
The deployment works on Heroku. I now receive an email to download the file.
Like Chika pointed out, you seem to have the old landing page. Please pull staging to update your branch and then raise another PR.

**Comment by emmabaye** [comment]
I think there is no need for me to update my PR since it doesn't conflict with staging branch. Isn't it only my changes that will be merged?

**Comment by emmabaye** [comment]
Pull request has been updated with staging branch.

**Pull request merged**
