### PR TITLE
Feat/cancel order/#157906018

### PR DESCRIPTION
**Pull request by Orlayhemmy**
### What does this PR do?
Add cancel order option

### Description of tasks to be completed
Differentiate between digital and physical product
Show cancel order button when the order is less than 2days old
Prevent user from canceling digital products order
Deduct shipping cost when an order is canceled after 24hrs
Send notification when the user cancels his order

### How should this be manually tested ?
Clone the repository and run reaction. Open the browser and go to 127.0.0.1:3000. Buy a product and checkout, a cancel button will be revealed

### Any relevant pivotal tracker stories ?
#157906018

### CODE REVIEW

**Review by amarachukwu-agbo — COMMENTED** [review]
Good job, it works fine on Heroku.

**Review by kenoseni — COMMENTED** [review]
@Orlayhemmy  Good job

**Comment by emmabaye** [comment]
Good job. Feature is working.

**Review by emmabaye — APPROVED** [review]
Good job. Feature is working.

**Pull request closed without merging**
