### PR TITLE
#157906014 Onboard customers 

### PR DESCRIPTION
**Pull request by kenoseni**
#### What does this PR do?
Users should be on-boarded into the app on signup or take a tour at any other time 

#### Description of Task to be completed?
Onboard users when they signup to the app for the first time.
Onboard users when they sign in and click __Take  Tour__

#### How should this be manually tested?
When a user visits the site for the first time and signs up, the user should be taken on a tour of the shop
when a user signs in and clicks on __Take Tour__ , the user should be taken on a tour of the shop

#### What are the relevant pivotal tracker stories?
#157906014

#### Screenshot
screen shot 2018-06-04 at 6 00 26 pm

### CODE REVIEW

**Comment by andela-moe** [comment]
@amarachukwu-agbo @Spectrumsun Why is it that we do not have a deployment for this PR?

**Comment by amarachukwu-agbo** [comment]
I apologise for this. There was a problem creating a review app on Heroku
for the two open PRs because the app.json was not updated. I have updated
it now and the PRs will be deployed soon.

**Comment by chuzksy-codeactive** [comment]
@kenoseni I enjoyed my tour around the app, nice feature and job well done. However, there is a little thing we have to change. When the mouse hovers the `Take Tour` button this is what we have
screen shot 2018-06-06 at 5 04 01 am
So, I will like us to change it to what we have on the  image below when the mouse hovers on the `Take Tour` button
screen shot 2018-06-06 at 5 01 52 am
I will provide you with some css styles to add to the class you used. Add the following styles to your class.

    height: 55px;
    flex: 0 0 auto;
    padding: 0px 17.5px;

You can always reach out to me if you are facing any difficulty implementing this.
That will do the job. Great job @kenoseni

**Comment by kenoseni** [comment]
Good observation @chuzksy-codeactive and thanks for the style.

**Comment by andela-moe** [comment]
Looks good to me

**Pull request merged**
